CREATE TABLE IF NOT EXISTS [adventure] (
	[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
	[index] INTEGER NULL,
	[typename] NVARCHAR(100) NULL,
	[name] NVARCHAR(100) NULL,
	[used] INTEGER NULL,
	[times] INTEGER NULL,
	[gold] INTEGER NULL,
	[exp] INTEGER NULL,
	[appear] NVARCHAR(100) NULL
)